name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo update -p ed25519-dalek@3.0.0 --precise 2.1.1
      - run: cargo build --target wasm32-unknown-unknown --release
      - run: cargo test
      - run: cargo clippy --all-targets -- -D warnings
